### PR TITLE
Updating Paper-onboarding features for Android

### PR DESCRIPTION
**Pull request by StreethawkNick**
Since Paper-onboarding iOS version is different to Android in terms of features:

>      ("BIG_IMAGE1", "Title", "Description text", "IconName1", "BackgroundColor", textColor, DescriptionColor, textFont, DescriptionFont)

 I have added TypeFace and Color features to text and description. This will make the Android version look consistent.

### CODE REVIEW

**Comment by rockerhieu** [comment]
I don't think we should hard code the typeface but let the theme decide instead.

**Comment by StreethawkNick** [comment]
i think it should be consistent with iOS. Why have Android's version Paper-onboarding different to the iOS?

**Comment by jagguli** [comment]
@rockerhieu I think it falls back to theme value if typeface is not give. Am I right @StreethawkNick

**Comment by rockerhieu** [comment]
@jagguli only if the widget constructor accept the origin context (activity, contextwrapper...). Right now it always uses `context.getApplicationText()` and that's the problem.

**Comment by StreethawkNick** [comment]
Will close this Pull Request in support of the other Pull Request  https://github.com/Ramotion/paper-onboarding-android/pull/19  @rockerhieu

**Pull request closed without merging**
